name: Deploy to Fly.io

on:
  push:
    branches: [master]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run validation
        run: npm run validate

      - name: Run tests
        run: npm run test:coverage

      - name: Build TypeScript
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy application
        run: |
          if [ -z "${FLY_API_TOKEN}" ]; then
            echo "Missing FLY_API_TOKEN secret" >&2
            exit 1
          fi
          if [ -z "${FLY_APP_NAME}" ]; then
            echo "Missing FLY_APP_NAME secret" >&2
            exit 1
          fi
          flyctl deploy \
            --remote-only \
            --config fly.toml \
            --app "${FLY_APP_NAME}" \
            --image-label "${GITHUB_SHA::7}"
