name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE: discord-bot
  REPO: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/discord/discord-bot

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push image
        run: |
          TAG=${GITHUB_SHA::7}
          docker build -t $REPO:$TAG .
          docker push $REPO:$TAG
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image $REPO:${TAG} \
            --region $REGION \
            --allow-unauthenticated \
            --min-instances=1 \
            --cpu=1 --memory=512Mi \
            --cpu-boost \
            --execution-environment gen2

      - name: Set env vars
        run: |
          gcloud run services update $SERVICE \
            --region $REGION \
            --set-env-vars DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }},CLIENT_ID=${{ secrets.CLIENT_ID }},GUILD_ID=${{ secrets.GUILD_ID }}