name: Deploy to Fly.io

on:
  push:
    branches: [master]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy application
        run: |
          if [ -z "${FLY_API_TOKEN}" ]; then
            echo "Missing FLY_API_TOKEN secret" >&2
            exit 1
          fi
          if [ -z "${FLY_APP_NAME}" ]; then
            echo "Missing FLY_APP_NAME secret" >&2
            exit 1
          fi
          flyctl deploy \
            --remote-only \
            --config fly.toml \
            --app "${FLY_APP_NAME}" \
            --image-label "${GITHUB_SHA::7}"
